language: python

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov

script: nosetests --where test --with-xunit --with-coverage

after_success:
  - codecov

branches:
  only:
    - master
