language: python

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install .

script: nosetests --where test --with-xunit

branches:
  only:
    - master
